drawings/urls.py
from django.urls import path, include
from . import views
import utils

app_name = 'drawings'
urlpatterns = [
    path('', views.index, name='index'),
    path('drawings/<int:item_id>/', views.drawing_detail, name='drawing_detail'),
]

learningProjectBlog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='about/', permanent=True)),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('about/', include('about.urls')),
    path('my-toys/', include('my_toys.urls')),
    path('drawings/', include('drawings.urls')),
    path('crafts/', include('crafts.urls')),
    path('lifehacks/', include('lifehacks.urls')),
    path('activities/', include('activities.urls')),
    path('poets/', include('poets.urls')),
    path('like/', include('like.urls')),
    # path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

like/urls.py
from django.urls import path
from .views import like_view

app_name = 'like'
urlpatterns = [
    path('', like_view, name='like_view'),
]

drawings/models.py
import PIL
from ckeditor.fields import RichTextField
from django.db import models
from django.utils import timezone
from media.models import Image
from PIL import Image as PILImage


class Drawings(models.Model):
    image = models.ForeignKey(Image, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Изображение')
    name = models.CharField(max_length=50, null=True, blank=True, verbose_name='Название')
    content = RichTextField(null=True, blank=True, verbose_name='Текст')
    is_published = models.BooleanField(default=False, verbose_name='Опубликовано?')
    date_painting = models.DateField(null=True, blank=True, verbose_name='Дата рисования')
    date_created = models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')
    date_published = models.DateField(null=True, blank=True, verbose_name='Дата публикации')

    def __str__(self):
        return self.name if self.name else 'неизвестный'

    def save(self, *args, **kwargs):
        if self.is_published:
            self.date_published = timezone.now()
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Рисунки'

drawings/views.py
from utils import detail_view, index_view

def index(request):
    '''Функция вывода общего контента'''
    return index_view(request, 'drawings', 'creativity/drawings/index.html')

def drawing_detail(request, item_id):
    '''функция вывода детальной информации с комментариями'''
    return detail_view(request, item_id, 'drawings', 'creativity/drawings/drawing.html')

templates/creativity/drawings/drawing.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ item.name }}{% endblock %}

{% block image %}
    <div class="block-last">
        <a class="last" href="{% url 'drawings:index' %}"><-- Назад</a>
    </div>
    <div class="row">
        <img class="img-drawing col-12 p-0" src="{{ item.image.image.url }}" alt="{{ item.name }}">
    </div>
{% endblock %}

{% block header %}
    <h1 class="text-center mt-5 header-content">{{ item.name }}</h1>
{% endblock %}

{% block content %}
    <div class="text-full">{{ item.content|safe }}</div>
    <div class="d-flex justify-content-between">
        <div class="pt-5">
            {% if item.date_crafting %}
                <span class="card-subtitle d-block text-start">Дата рисования: {{ item.date_painting }}</span>
            {% else %}
                <span class="card-subtitle d-block text-start">Дата рисования: неизвестно</span>
            {% endif %}
            <span class="card-subtitle d-block text-start">Дата публикации: {{ item.date_published }}</span>
        </div>
        
        {% include 'likes/likes.html' with liked=liked item=item like_count=like_count %}
    </div>
    {% include 'comments/comments.html' with comments=comments form=form %}
{% endblock %}

templates/creativity/drawings/index.html
{% extends 'base.html' %}

{% block header %}<h1 class="header-content">Галерея рисунков</h1>{% endblock %}

{% block content %}
    <div class="content-about">
    {% if item_list %}
        <div class="row">
            {% for item in item_list %}
            <div class="col-xxl-4 col-xl-4 col-lg-6 col-md-6 col-sm-12 col-12 mb-5">
                <div class="card">
                    <a href="{% url 'drawings:drawing_detail' item.id %}">
                        <img src="{{ item.image.image.url }}" class="card-img-top" alt="{{ item.name }}">
                        {% if item.is_recent %}
                            <span class="position-absolute top-0 start-100 translate-middle p-2 bg-danger border border-light rounded-circle">
                        {% endif %}
                    </a>
                    <h3 class="card-title ps-2">{{ item.name }}</h3>
                </div>
                <div class="card-body bg-info ps-2 rounded-bottom-2">
                    <span class="card-subtitle">
                        {% if item.date_painting %}
                            Дата рисования: {{ item.date_painting }}<br>
                        {% else %}
                            Дата рисования: Неизвестно<br>
                        {% endif %}
                            Дата публикации: {{ item.date_published }}<br>
                    </span>
                </div>
            </div>
            {% endfor %}
        </div>
    {% else %}
        <p class="fs-2 t">Этот раздел пока в разработке!</p>
    {% endif %}
    </div>
{% endblock %}