about/urls.py
from django.urls import path
from . import views

app_name = 'about'
urlpatterns = [
    path('', views.index, name='index'),
]

learningProjectBlog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='about/', permanent=True)),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('about/', include('about.urls')),
    path('my-toys/', include('my_toys.urls')),
    path('drawings/', include('drawings.urls')),
    path('crafts/', include('crafts.urls')),
    path('lifehacks/', include('lifehacks.urls')),
    path('activities/', include('activities.urls')),
    path('poets/', include('poets.urls')),
    path('like/', include('like.urls')),
    # path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

like/urls.py
from django.urls import path
from .views import like_view

app_name = 'like'
urlpatterns = [
    path('', like_view, name='like_view'),
]

my_toys/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'my_toys'
urlpatterns = [
    path('', views.index, name='index'),
    path('toys/<int:item_id>/', views.toy_detail, name='toy_detail'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript" src="{% static 'js/yandex_metrika.js' %}"></script>
    <noscript><div><img src="https://mc.yandex.ru/watch/99492750" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'favicon-32x32.png' %}"><!--32x32-->
	<title>{% block title %}Ксюшка - носик, два ушка{% endblock %}</title>
	<!-- Подключаем стили -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="{%  static 'css/style.css' %}">
</head>
<body>
	<main class="main">
		<div class="container">
            <div class="row pt-5">

                <div class="col-xxl-1 col-xl-1 col-lg-1 col-1">
                    <img class="logo" src="{% static 'logo.png' %}" alt="">
                </div>

                <div class="nav-mt col-xxl-8 offset-xxl-3 col-xl-8 offset-xl-3 col-lg-10 offset-lg-1 col-md-12 offset-md-0 col-sm-12 offset-sm-0 col-12 offset-0">
                    <nav>
                        <ul class="d-flex justify-content-between">
                            <li><a href="{% url 'about:index' %}">Обо мне</a></li>
                            <li><a href="{% url 'my_toys:index' %}">Мои игрушки</a></li>
                            <li class="dropdown"><a href="#" class="dropdown-toggle">Творчество</a>
                                <ul class="dropdown-menu">
                                    {% for section in sections_list %}
                                        <li><a href="{{ section.get_url }}">{{ section.name_section }}</a></li>
                                    {% endfor %}
                                </ul>
                            </li>
                            {% if user.is_authenticated %}
                                <li class="logout">
                                    <div class="log-mob">
                                        <span>{{ user.username }}</span><br>
                                        <a href="{% url 'logout' %}?next={{ request.path }}">Выйти</a>
                                    </div>
                                </li>
                            {% else %}
                                <li class="login">
                                    <div class="log-mob">
                                        <a href="{% url 'login' %}">Войти</a><br>
                                        <a href="{% url 'signup' %}">Регистрация</a>
                                    </div>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>

            </div><!-- row -->
            
            <div class="row pb-5">
                <div class="human col-12">
                    <img class="main-age" src="" alt="">
                    {% if info_list|length > 0 %}
                        {% include 'information/info_cloud.html' %}
                    {% endif %}
                </div>
            </div>
		</div><!-- container -->
	</main>

	<section style="background-color: #1fbc23;">
		<div class="container">
            {% block image %}{% endblock %}
            {% block header %}{%  endblock %}
            {% block content %}{% endblock %}
		</div>
	</section>

	<footer class="d-flex flex-column align-items-end pe-5">
        <div class="mt-auto">
			<p class="h3 pb-5">
				Блог создан <a class="bg-transparent" href='mailto:sergedoroshenk@yandex.ru'>мной</a> в качестве тренировки и для развлечения ребенка.
			</p>
        </div>
{#        <div class="">#}
{#            <p class="h5"><span>## Условия использования изображений:</span>#}
{#                <br>- Все изображения, представленные на этом сайте, являются собственностью [имя автора или сайта] и защищены авторскими правами.#}
{#            </p>#}
{#            <p class="h5"><span>### Разрешённые способы использования:</span>#}
{#                <br>- Вы можете использовать изображение для личных, некоммерческих целей, при условии указания авторства.#}
{#                <br>- Запрещено использовать изображения в коммерческих целях без предварительного письменного разрешения.#}
{#                <br>- Запрещено изменять, адаптировать или создавать производные работы на основе изображений без разрешения.#}
{#            </p>#}
{#        </div>#}
	</footer>

	<!-- Скрипты -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/age_and_comments.js' %}"></script>
	<script src="{% static 'js/like.js' %}"></script>
    <script>
        const myAge = '2016, 7, 23';
        const staticPath = '{% static '' %}';
	    const mediaPath = '{{ MEDIA_URL }}';
        const isAuthenticated = {{ user.is_authenticated|yesno:'true,false' }};
        const csrfToken = '{{ csrf_token }}';
    </script>
</body>
</html>

templates/base_old.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}Ксюшка - носик, два ушка{% endblock %}</title>
	<!-- Подключаем стили -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="{%  static 'css/style.css' %}">
</head>
<body>
	<main class="main">
		<div class="container">
			<div class="main-header">
				<div class="row">

					<div class="col-xxl-1 col-xl-1 col-lg-1 col-1">
                        <img class="main-logo" src="{% static 'img/logo.png' %}" alt="">
					</div>

					<div class="col-xxl-8 offset-xxl-3 col-xl-8 offset-xl-3 col-lg-8 offset-lg-3 col-8">
						<nav>
							<ul class="d-flex justify-content-between">
								<li><a href="{% url 'about:index' %}">Обо мне</a></li>
								<li><a href="{% url 'my_toys:index' %}">Мои игрушки</a></li>
								<li><a href="#">Творчество</a>
									<ul>
                                        {% for section in sections_list %}
                                            <li><a href="{{ section.get_url }}">{{ section.name_section }}</a></li>
                                        {% endfor %}
									</ul>
								</li>
                                {% if user.is_authenticated %}
                                    <li class="logout">
                                        <span>{{ user.username }}<br></span>
                                        <a href="{% url 'logout' %}?next={{ request.path }}">Выйти</a>
                                    </li>
                                {% else %}
                                    <li class="login">
                                        <a href="{% url 'login' %}">Войти</a><br>
                                        <a href="{% url 'signup' %}">Регистрация</a>
                                    </li>
                                {% endif %}
							</ul>
						</nav>


					</div>

				</div><!-- row -->
				<div class="">
					<img class="main-age" src="{% static 'img/main/2.png' %}" alt="7-16">
{#					<img src="{% static 'img/main/2-shadow.png' %}" alt="">#}
{#					<img src="{% static 'img/main/3-shadow.png' %}" alt="7-16">#}
{#					<img src="{% static 'img/main/4-shadow.png' %}" alt="">#}
{#					<img src="{% static 'img/main/5-shadow.png' %}" alt="">#}
{#					<img src="{% static 'img/main/6-shadow.png' %}" alt="">#}
{#					<img src="{% static 'img/main/7-shadow.png' %}" alt="">#}
{#					<img src="{% static 'img/main/8-shadow.png' %}" alt="">#}
				</div>
			</div><!-- main-header -->
		</div><!-- container -->
	</main>

	<section class="content">
		<div class="container">
            {% block image %}{% endblock %}
            {% block header %}{%  endblock %}
            {% block content %}{% endblock %}
		</div>
		<div class="content-footer"></div>
	</section>

	<footer class="d-flex flex-column align-items-end pe-5">
        <div class="mt-auto">
			<p class="h3 pb-5">
				Блог создан <a class="bg-transparent" href='mailto:sergedoroshenk@yandex.ru'>мной</a> в качестве тренировки и для развлечения ребенка.
			</p>
        </div>
{#        <div class="">#}
{#            <p class="h5"><span>## Условия использования изображений:</span>#}
{#                <br>- Все изображения, представленные на этом сайте, являются собственностью [имя автора или сайта] и защищены авторскими правами.#}
{#            </p>#}
{#            <p class="h5"><span>### Разрешённые способы использования:</span>#}
{#                <br>- Вы можете использовать изображение для личных, некоммерческих целей, при условии указания авторства.#}
{#                <br>- Запрещено использовать изображения в коммерческих целях без предварительного письменного разрешения.#}
{#                <br>- Запрещено изменять, адаптировать или создавать производные работы на основе изображений без разрешения.#}
{#            </p>#}
{#        </div>#}
	</footer>

	<!-- Скрипты -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/age_and_comments.js' %}"></script>
	<script src="{% static 'js/like.js' %}"></script>
    <script>
        const myAge = '2016, 7, 23';
        const staticPath = '{% static '' %}';
        const isAuthenticated = {{ user.is_authenticated|yesno:'true,false' }};
        const csrfToken = '{{ csrf_token }}';
    </script>
</body>
</html>